#include<bits/stdc++.h>
using namespace std;
int s1,s2;
char tmp[1000005];
stack<int> a1;
stack<char> a2;
void yunsuan(int l,int r)
{
	while(l<=r)
	{
		if((tmp[l]=='0')||(tmp[l]=='1'))
		{
			a1.push(tmp[l]-'0');
		}
		else
		{
			if(tmp[l]=='(')
			{
				int p=l;
				a2.push('(');
				while(!a2.empty())
				{
					p++;
					if(tmp[p]=='(')
					{
						a2.push('(');
					}
					if(tmp[p]==')')
					{
						a2.pop();
					}
				}
				yunsuan(l+1,p-1);
				l=p;
			}
			else
			{	
				int t=a1.top();a1.pop();
				if((t==0)&&(tmp[l]=='&'))
				{
					s1++;
					l++;
					if(tmp[l]=='(')
					{
						a2.push('(');
						while(!a2.empty())
						{
							l++;
							if(tmp[l]=='(')
							{
								a2.push('(');
							}
							if(tmp[l]==')')
							{
								a2.pop();
							}
						}
					}
					a1.push(0);
				}
				else if((t==1)&&(tmp[l]=='|'))
				{
					s2++;
					l++;
					while((tmp[l]!='|')&&(l<=r))
					{
						if(tmp[l]=='(')
						{
							a2.push('(');
							while(!a2.empty())
							{
								l++;
								if(tmp[l]=='(')
								{
									a2.push('(');
								}
								if(tmp[l]==')')
								{
									a2.pop();
								}
							}
						}
						l++;
					}
					l--;
					a1.push(1);
				}
				else
				{
					int t1,lt;
					if(tmp[l+1]=='(')
					{
						int p=l+1;
						a2.push('(');
						while(!a2.empty())
						{
							p++;
							if(tmp[p]=='(')
							{
								a2.push('(');
							}
							if(tmp[p]==')')
							{
								a2.pop();
							}
						}
						yunsuan(l+2,p-1);
						lt=p+1;
						t1=a1.top();a1.pop();
					}
					else
					{
						t1=tmp[l+1]-'0';
						lt=l+1;
					}
					if(tmp[l]=='&')
					{
						a1.push(t&t1);
						l=lt;
					}
					else
					{
						if(lt<=r-1)
						{	
							int p=lt+1;
							while((tmp[p]!='|')&&(p<=r))
							{
								if(tmp[p]=='(')
								{
									a2.push('(');
									while(!a2.empty())
									{
										p++;
										if(tmp[p]=='(')
										{
											a2.push('(');
										}
										if(tmp[p]==')')
										{
											a2.pop();
										}
									}
								}
								p++;
							}
							yunsuan(lt,p-1);
							t1=a1.top();a1.pop();
							a1.push(t|t1);
							l=p-1;
						}
						else
						{
							a1.push(t|t1);
							l=lt-1;
						}
					}
				}
			}
		}
		l++;
	}
}
int main ()
{
	freopen("expr.in","r",stdin);
	freopen("expr.out","w",stdout);
	scanf("%s",tmp);
	yunsuan(0,strlen(tmp)-1);
	printf("%d\n%d %d",a1.top(),s1,s2);
}
